Labb1-asp.net-CorporateDbLeaveApplication/Controllers/LeaveApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Labb1_asp.net_CorporateDbLeaveApplication.Data;
using Labb1_asp.net_CorporateDbLeaveApplication.Models;
using Labb1_asp.net_CorporateDbLeaveApplication.Models.ViewModels;
using Labb1_asp.net_CorporateDbLeaveApplication.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Labb1_asp.net_CorporateDbLeaveApplication.Controllers
{
    [Authorize]
    public class LeaveApplicationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public LeaveApplicationController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: LeaveApplication
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["DateSortParm"] = string.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                return NotFound(); // Or any appropriate action if user is not found
            }

            IQueryable<LeaveApplication> leaveApplicationsQuery = _context.LeaveApplications.Include(l => l.Employee);

            switch (sortOrder)
            {
                case "date_desc":
                    leaveApplicationsQuery = leaveApplicationsQuery.OrderByDescending(l => l.ApplicationSubmissionDate);
                    break;
                default:
                    leaveApplicationsQuery = leaveApplicationsQuery.OrderBy(l => l.ApplicationSubmissionDate);
                    break;
            }

            List<LeaveApplication> leaveApplications;

            leaveApplications = await leaveApplicationsQuery
                .Where(l => l.Employee.ApplicationUserId == currentUser.Id).ToListAsync();


            var leaveApplicationViewModels = leaveApplications.Select(la => new LeaveApplicationViewModel
            {
                EmployeeId = la.FkEmployeeId,
                employee = la.Employee,
                StartDate = la.StartDate,
                EndDate = la.EndDate,
                TypeOfLeave = la.TypeOfLeave,
                ApplicationSubmissionDate = la.ApplicationSubmissionDate,
                LeaveApplicationId = la.LeaveApplicationId, // Assuming you have an Id property in LeaveApplication
                ApplicationStatus = la.ApplicationStatus // Assuming you have an ApplicationStatus property
            }).ToList();

            return View(leaveApplicationViewModels);
        }
        // GET: LeaveApplication
        public async Task<IActionResult> ManagerIndex(string sortOrder)
        {
            ViewData["DateSortParm"] = string.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                return NotFound(); // Or any appropriate action if user is not found
            }

            IQueryable<LeaveApplication> leaveApplicationsQuery = _context.LeaveApplications.Include(l => l.Employee);

            switch (sortOrder)
            {
                case "date_desc":
                    leaveApplicationsQuery = leaveApplicationsQuery.OrderByDescending(l => l.ApplicationSubmissionDate);
                    break;
                default:
                    leaveApplicationsQuery = leaveApplicationsQuery.OrderBy(l => l.ApplicationSubmissionDate);
                    break;
            }

            List<LeaveApplication> leaveApplications;
            if (User.IsInRole(SD.Role_Manager))
            {
                leaveApplications = await leaveApplicationsQuery.ToListAsync();
            }
            else
            {
                return Forbid(); // If user doesn't have a valid role
            }

            var leaveApplicationViewModels = leaveApplications.Select(la => new LeaveApplicationViewModel
            {
                EmployeeId = la.FkEmployeeId,
                employee = la.Employee,
                StartDate = la.StartDate,
                EndDate = la.EndDate,
                TypeOfLeave = la.TypeOfLeave,
                ApplicationSubmissionDate = la.ApplicationSubmissionDate,
                LeaveApplicationId = la.LeaveApplicationId, // Assuming you have an Id property in LeaveApplication
                ApplicationStatus = la.ApplicationStatus // Assuming you have an ApplicationStatus property
            }).ToList();

            return View(leaveApplicationViewModels);
        }

        // GET: LeaveApplication/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveApplication = await _context.LeaveApplications
                .FirstOrDefaultAsync(m => m.LeaveApplicationId == id);
            if (leaveApplication == null)
            {
                return NotFound();
            }
            return View(leaveApplication);
        }

        // GET: LeaveApplications/Create
        public IActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Name");
            return View();
        }
        // POST: LeaveApplications/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,StartDate,EndDate,TypeOfLeave,ApplicationSubmissionDate,ApplicationStatus")] LeaveApplicationViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    return NotFound(); // Eller annan lämplig åtgärd om användaren inte hittas
                }

                var employee = await _context.Employees.SingleOrDefaultAsync(e => e.ApplicationUserId == user.Id);
                if (employee == null)
                {
                    // Hantera fallet där Employee inte hittas
                    return NotFound(); // Eller returnera en annan vy eller åtgärd
                }

                var leaveApplication = new LeaveApplication
                {
                    FkEmployeeId = employee.EmployeeId,
                    StartDate = viewModel.StartDate,
                    EndDate = viewModel.EndDate,
                    TypeOfLeave = viewModel.TypeOfLeave,
                    ApplicationSubmissionDate = DateTime.Now,
                    ApplicationStatus = ApplicationStatus.Pending
                };

                _context.Add(leaveApplication);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Name", viewModel.EmployeeId);
            return View(viewModel);
        }



        // GET: LeaveApplication/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveApplication = await _context.LeaveApplications
                .Include(l => l.Employee)
                .FirstOrDefaultAsync(m => m.LeaveApplicationId == id);

            if (leaveApplication == null)
            {
                return NotFound();
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "FullName", leaveApplication.FkEmployeeId);
            return View(leaveApplication);
        }

        // POST: LeaveApplication/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LeaveApplicationId,FkEmployeeId,StartDate,EndDate,TypeOfLeave,ApplicationStatus, ApplicationSubmissionDate")] LeaveApplication leaveApplication)
        {
            if (id != leaveApplication.LeaveApplicationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var employee = await _context.Employees.FindAsync(leaveApplication.FkEmployeeId);
                    if (employee == null)
                    {
                        ModelState.AddModelError("FkEmployeeId", "Invalid employee");
                        ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "FullName", leaveApplication.FkEmployeeId);
                        return View(leaveApplication);
                    }

                    _context.Update(leaveApplication);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveApplicationExists(leaveApplication.LeaveApplicationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "FullName", leaveApplication.FkEmployeeId);
            return View(leaveApplication);
        }




        // GET: LeaveApplication/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveApplication = await _context.LeaveApplications

Labb1-asp.net-CorporateDbLeaveApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Labb1_asp.net_CorporateDbLeaveApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Labb1_asp.net_CorporateDbLeaveApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Labb1_asp.net_CorporateDbLeaveApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Labb1_asp.net_CorporateDbLeaveApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Labb1-asp.net-CorporateDbLeaveApplication/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Corporate Db for Leave Applications</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Labb1_asp.net_CorporateDbLeaveApplication.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <!-- First navbar -->
        <nav class="navbar navbar-expand-lg navbar-up navbar-tight">
            <div class="container-fluid">
                <!-- Logo to the left -->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" alt="Logo" width="auto" height="80" class="d-inline-block align-top">
                </a>


                <!-- Partial for login to the right -->
                <div class="collapse navbar-collapse justify-content-end mx-3" id="navbarSupportedContent">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        @if (User.Identity.IsAuthenticated)
        {
            <!-- Second navbar -->
            <div class="navbar-outer">
                <nav class="navbar navbar-expand-lg navbar-light navbar-tight navbar-inner">
                    <div class="container-fluid">
                        <!-- Menu to the left -->
                        <ul class="navbar-nav">
                            @if (User.IsInRole("Employee"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="LeaveApplication" asp-action="Index">My leave requests</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="LeaveApplication" asp-action="ManagerIndex">Manage leave requests</a>
                                </li>
                            }
                        </ul>
                        |
                        <ul class="navbar-nav">
                            @if (User.IsInRole("Manager"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="LeaveApplication" asp-action="Index">My leave requests</a>
                                </li>
                            }

                        </ul>

                        <!-- "Apply for new leave to the right -->
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item">
                                <a class="btn-leave nav-link" asp-area="" asp-controller="LeaveApplication" asp-action="Create">
                                    <span>Apply for new leave</span>
                                </a>
                            </li>
                        </ul>

                        <!-- Button for mobile view -->
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#secondNavbar"
                                aria-controls="secondNavbar" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </nav>
            </div>
        }
    </header>

    <!-- Main content -->
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Corporate Db - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>